#+title: M.Tech Projects
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css" />
#+OPTIONS: html-style:nil toc:nil title:nil num:nil timestamp:nil
#+INCLUDE: ../logo.org
#+begin_export html
<script> document.querySelectorAll("#mySideNav a#projects")[0].classList.add("active"); </script>
#+end_export

* Communications Projects
** OFDM
- M.Tech 1st Semester
- Software used: MATLAB and Simulink
Implemented an OFDM system on Simulink. Performed simulation and analysis of OFDM system based on simulink.
** Finite field arithmetic
- PhD 2nd year
- Implemented on Python
Wrote python modules for finite field arithmetic. Some linear algebra operations and Reed solomon decoder was also implemented for finite fields with prime order.

* Computer Vision and Image Processing Projects
** Image Segmentation using Watershed Transform
- M.Tech 1st Semester
- Team Size: 2
- Software Used: MATLAB and Python
Implemented immersion simulations on grayscale images to segment different regions by using watershed transform.

** Image mosaic using homography estimation
- M.Tech 2nd Semester
- Software used: MATLAB
Stiched five images taken of a subject from five different viewpoints to create a mosaic. Implemented SIFT matching from ~vlfeat.org~ and used homography estimation using normalization of scales to morph images to stich them in a mosaic.

** Finding rotation and translation direction using two images
- M.Tech 2nd Semester
- Software used: MATLAB
Computed the rotation and translation direction between two images using the Hartley normalization for the eight point algorithm. Matching points were computed using SIFT and outliers removed using RANSAC.
