#+title: Kanishak | Home
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./style.css" />
#+OPTIONS: html-style:nil toc:nil title:nil num:nil timestamp:nil
#+INCLUDE: ./logo.org

#+begin_export html
<script> document.querySelectorAll("#mySideNav a#home")[0].classList.add("active"); </script>
#+end_export

* About Me
I am a Senior Engineer at Qualcomm Bangalore, India. As part of Wireless Research and Development (WRD) team, my current area of focus is on cutting edge communication technologies.

Prior to joining Qualcomm, I completed my *PhD from the Indian Institute of Science, Bangalore*, with a research interest in wireless distributed systems. During my PhD, I have worked on distributed machine learning systems, broadcast networks for information retrieval and delivery, and wireless cache-aided networks, focusing on privacy and security.

After acquiring AIR 10 in GATE (EC) 2018, I joined IISc for an M.Tech in signal processing and upgraded to a PhD after one year. I have hands-on experience in image processing and computer vision projects. I also have a strong background in coding and information theory.
-----
** Achievements
- Received Prime Minister's Research Fellowship (PMRF) from January 2020 to July 2023
- Achieved All India Rank 10 in GATE EC 2018. GATE Score: 1000
- Achieved All India Rank 30 in Junior Mathematical Olympiad 2011
-----
** Technical Skills
- *PROGRAMMING:* Python, Octave/MATLAB, C/C++, Bash scripting
- *SOFTWARE TOOLS:* LTspice, LabView, Arduino IDE, SimuLink
- *MISCELLANEOUS:* Linux, SSH, git, $\LaTeX$, HTML/CSS, vim, emacs
-----
** Relevant Courses
| *Matrix Theory*         | Random Process                 |
| Error Control Coding    | *Digital Communication*        |
| *Machine Learning*      | Detection and Estimation       |
| Optimization            | *Space Time Signal Processing* |
| *Computer Vision*       | Digital Image Processing       |
| Time Frequency Analysis | *Wireless Communication*       |
-----
*** Useful links
| [[https://kanishakvaidya.github.io/resume][Resume]] | [[https://www.linkedin.com/in/kanishakvaidya/][LinkedIn]] | [[mailto:kanishakvaidya@gmail.com][Email]] |
